inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml
inherit_from:
  - .rubocop_suppress_temp.yml
inherit_mode:
  merge:
    - Exclude
AllCops:
  Exclude:
    - 'db/schema.rb'
