Layout/SpaceBeforeComma:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Layout/Tab:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Style/SymbolProc:
  Enabled: true
Style/NumericLiterals:
  Enabled: true
Style/Encoding:
  Enabled: false
Layout/EmptyLines:
  Enabled: true
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Layout/AlignParameters:
  Enabled: true
Style/WordArray:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Layout/IndentHash:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Layout/MultilineBlockLayout:
  Enabled: false
Layout/SpaceAfterColon:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
Layout/FirstParameterIndentation:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Style/UnneededInterpolation:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/GuardClause:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/BlockEndNewline:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/DateTime:
  Enabled: false
Layout/SpaceInLambdaLiteral:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/SelfAssignment:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/BlockComments:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/Alias:
  Enabled: false
Style/ClassCheck:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Naming/VariableName:
  Enabled: false
Style/InverseMethods:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Layout/BlockAlignment:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Layout/SpaceInsideReferenceBrackets:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Style/ClassMethods:
  Enabled: false
GitHub/RailsControllerRenderPathsExist:
  Enabled: false
Layout/DefEndAlignment:
  Enabled: false
